app = "lolly-backend"

primary_region = "sjc"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 5
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150

[[services.ports]]
  handlers = ["http"]
  port = 80

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[services.tcp_checks]
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"

[mounts]
  source = "lolly_audio_data"
  destination = "/app/audios"