app = "lolly-redis"
primary_region = "sjc"

[build]
  image = "flyio/redis:6.2.6"

[env]
  REDIS_ARGS = "--requirepass ${REDIS_PASSWORD}"

[metrics]
  port = 9091
  path = "/metrics"

[[mounts]]
  source = "lolly_redis_data"
  destination = "/data" 