app = "lolly-worker"
primary_region = "sjc"

[build]
  dockerfile = "Dockerfile.worker"

[env]
  NODE_ENV = "production"
  PORT = "8081"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 5
  
# Workers don't need to handle HTTP traffic directly,
# but we keep a health check endpoint
[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"

[mounts]
  source = "lolly_audio_data"
  destination = "/app/audios" 